language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install codecov
  - pip install -e .
  - pip install -r dev_requirements.txt
# command to run tests
script:
  - py.test --cov=./
# Collect coverage
after_success:
  - codecov